services:
  - type: web
    name: hello-nest
    env: node
    plan: free
    region: singapore
    buildCommand: yarn install && yarn build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
